<?php
/**
 * Leobo Custom Booking System - Multi-Step Booking Form Template
 * Matches the exact design from the provided images
 * 
 * @package LeoboCustomBookingSystem
 * @version 3.0.0
 */

// Prevent direct access
if (!defined('ABSPATH')) {
    exit;
}

$form_id = $args['form_id'] ?? 'leobo-booking-form';
$atts = $args['attributes'] ?? array();
?>

<div id="leobo-booking-system" class="leobo-booking-wrapper">
    
    <!-- Header Progress -->
    <div class="booking-header-progress">
        <div class="progress-step active" data-step="1">
            <span class="step-icon">📅</span>
            <span class="step-text">AVAILABILITY CHECK</span>
        </div>
        <div class="progress-step" data-step="2">
            <span class="step-icon">👁</span>
            <span class="step-text">TAILOR YOUR STAY</span>
        </div>
        <div class="progress-step" data-step="3">
            <span class="step-icon">👤</span>
            <span class="step-text">GUEST INFORMATION</span>
        </div>
        <div class="progress-step" data-step="4">
            <span class="step-icon">🧩</span>
            <span class="step-text">RESERVED & READY</span>
        </div>
    </div>

    <div class="booking-content-wrapper">
        
        <!-- Main Content Area -->
        <div class="booking-main-content">
            
            <form id="<?php echo esc_attr($form_id); ?>" class="leobo-booking-form" method="post">
                
                <!-- Step 1: Availability Check -->
                <div class="booking-step booking-step-1 active" data-step="1">
                    
                    <div class="step-content">
                        
                        <!-- Dates Section -->
                        <div class="form-section dates-section">
                            <h3 class="section-title">Dates</h3>
                            
                            <div class="date-input-wrapper">
                                <!-- Custom Date Picker -->
                                <div class="custom-date-picker">
                                    <div class="date-picker-trigger" id="date-picker-trigger">
                                        <div class="selected-dates">
                                            <div class="arrival-display">
                                                <span class="date-label">Arrival</span>
                                                <span class="date-value" id="arrival-display">Select date</span>
                                            </div>
                                            <div class="date-separator">→</div>
                                            <div class="departure-display">
                                                <span class="date-label">Departure</span>
                                                <span class="date-value" id="departure-display">Select date</span>
                                            </div>
                                        </div>
                                        <div class="date-picker-icon">📅</div>
                                    </div>
                                    
                                    <!-- Calendar Widget -->
                                    <div class="calendar-widget" id="calendar-widget" style="display: none;">
                                        <div class="calendar-header">
                                            <button type="button" class="calendar-nav prev-month" id="prev-month">‹</button>
                                            <div class="calendar-title" id="calendar-title">January 2024</div>
                                            <button type="button" class="calendar-nav next-month" id="next-month">›</button>
                                        </div>
                                        <div class="calendar-body">
                                            <div class="calendar-weekdays">
                                                <div class="weekday">Su</div>
                                                <div class="weekday">Mo</div>
                                                <div class="weekday">Tu</div>
                                                <div class="weekday">We</div>
                                                <div class="weekday">Th</div>
                                                <div class="weekday">Fr</div>
                                                <div class="weekday">Sa</div>
                                            </div>
                                            <div class="calendar-days" id="calendar-days">
                                                <!-- Days will be generated by JavaScript -->
                                            </div>
                                        </div>
                                        <div class="calendar-footer">
                                            <button type="button" class="btn btn-secondary" id="calendar-clear">Clear</button>
                                            <button type="button" class="btn btn-primary" id="calendar-apply">Apply</button>
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="date-info" id="date-range-info" style="display: none;">
                                    <span id="date-range-text"></span>
                                    <span id="nights-count"></span>
                                </div>
                                
                                <div class="date-availability-notice">
                                    📅 Different colors indicate seasonal pricing: <span style="color: #4caf50;">Green (Standard)</span>, <span style="color: #ff8f00;">Orange (Peak)</span>, <span style="color: #dc267f;">Pink (Christmas)</span>. Legend shows below calendar.
                                </div>
                                
                                <div class="date-flexible-option">
                                    <label class="checkbox-label">
                                        <input type="checkbox" id="flexible-dates" name="flexible_dates" />
                                        <span class="checkmark"></span>
                                        My dates are flexible
                                    </label>
                                </div>
                                
                                <!-- Hidden inputs for form submission -->
                                <input type="hidden" id="arrival-date" name="checkin_date" />
                                <input type="hidden" id="departure-date" name="checkout_date" />
                            </div>
                        </div>

                        <!-- Guests and What's Included Grid -->
                        <div class="guests-included-grid">
                            <!-- Guest Section -->
                            <div class="form-section guests-section">
                                
                                <!-- Adults -->
                                <div class="guest-type-row">
                                    <label class="guest-label">Adults</label>
                                    <div class="guest-counter">
                                        <button type="button" class="counter-btn minus" data-target="adults">-</button>
                                        <span class="counter-value" id="adults-count">1</span>
                                        <button type="button" class="counter-btn plus" data-target="adults">+</button>
                                    </div>
                                </div>

                                <!-- Children -->
                                <div class="guest-type-row">
                                    <label class="guest-label">Children (4+ years)</label>
                                    <div class="guest-counter">
                                        <button type="button" class="counter-btn minus" data-target="children">-</button>
                                        <span class="counter-value" id="children-count">0</span>
                                        <button type="button" class="counter-btn plus" data-target="children">+</button>
                                    </div>
                                </div>

                                <!-- Babies -->
                                <div class="guest-type-row">
                                    <label class="guest-label">Baby (0-3 years)</label>
                                    <div class="guest-counter">
                                        <button type="button" class="counter-btn minus" data-target="babies">-</button>
                                        <span class="counter-value" id="babies-count">0</span>
                                        <button type="button" class="counter-btn plus" data-target="babies">+</button>
                                    </div>
                                </div>
                                
                                <!-- Hidden inputs -->
                                <input type="hidden" id="adults" name="adults" value="1" />
                                <input type="hidden" id="children" name="children" value="0" />
                                <input type="hidden" id="babies" name="babies" value="0" />
                            </div>

                            <!-- What's Included Section -->
                            <div class="form-section included-section">
                                <h3 class="section-title">What's included in the price?</h3>
                                <ul class="included-list">
                                    <li>Exclusive use of entire 8000 hectare (20,000 acre) private reserve</li>
                                    <li>Full use of Observatory Villa with all facilities</li>
                                    <li>All meals, house drinks, wines and spirits included</li>
                                    <li>Chef, Butler, Game Ranger, and full staff</li>
                                    <li>Game Drives, Quad Bike Safari, Dirt Bike Safari, GS Moon Off-road Buggy</li>
                                    <li>Fishing, Day at Beach Camp, Afternoons at Mountain Lookout</li>
                                    <li>Rock Art Viewing, Clifftop Mountain Walks, Cave Walks</li>
                                    <li>Paint Balling, Clay Pigeon Shooting, Clifftop Camping, Hippo Camping</li>
                                    <li>Wood-fire Pizzas at Hippo Deck, Dinner at Romance Bush Deck</li>
                                    <li>Drinks at Bone Bar, Sunrise at River Lookout, Boma Dinners</li>
                                    <li>Research Grade Observatory with automated 20-inch telescope</li>
                                    <li>Heated Infinity Pool, Jacuzzi, 3D TV, Wi-Fi, Multi-room music system</li>
                                </ul>
                            </div>
                        </div>

                        <!-- Step Navigation -->
                        <div class="step-navigation">
                            <button type="button" class="btn btn-primary next-step" data-next="2">
                                NEXT
                            </button>
                        </div>
                    </div>
                </div>

                <!-- Step 2: Tailor Your Stay -->
                <div class="booking-step booking-step-2" data-step="2">
                    <div class="step-content">
                        
                        <h2 class="step-title">Tailor your stay</h2>
                        <p class="step-subtitle">The following are optional extras available for your stay, at additional costs:</p>

                        <!-- Arrival Section -->
                        <div class="form-section">
                            <h3 class="section-title">ARRIVAL</h3>
                            <p class="section-subtitle">Transfer requests?</p>
                            
                            <div class="checkbox-group">
                                <label class="checkbox-option">
                                    <input type="checkbox" name="transfer[]" value="private_helicopter" />
                                    <span class="checkmark"></span>
                                    Private helicopter transfer
                                </label>
                                <label class="checkbox-option">
                                    <input type="checkbox" name="transfer[]" value="road_transfer" />
                                    <span class="checkmark"></span>
                                    Road transfer by Leobo
                                </label>
                            </div>
                        </div>

                        <!-- Helicopter Package Section -->
                        <div class="form-section">
                            <h3 class="section-title">HELICOPTER PACKAGE</h3>
                            <p class="section-subtitle">Would you like to add a helicopter adventure package?</p>
                            
                            <div class="radio-group">
                                <label class="radio-option">
                                    <input type="radio" name="helicopter_interested" value="yes" id="helicopter-yes" />
                                    <span class="radio-mark"></span>
                                    Yes, I'm interested
                                </label>
                                <label class="radio-option">
                                    <input type="radio" name="helicopter_interested" value="no" id="helicopter-no" checked />
                                    <span class="radio-mark"></span>
                                    No thanks
                                </label>
                            </div>
                            
                            <!-- Helicopter Package Options (shown conditionally) -->
                            <div id="helicopter-options" class="helicopter-options" style="display: none; margin-top: 20px;">
                                <div class="helicopter-info-box" style="background: #f8f9fa; border: 1px solid #e9ecef; border-radius: 8px; padding: 15px; margin-bottom: 20px;">
                                    <h4 style="margin: 0 0 10px 0; color: #495057;">🚁 Helicopter Adventure Package</h4>
                                    <p style="margin: 0; font-size: 14px; color: #6c757d;">
                                        Includes return helicopter transfer from OR Tambo, flying hours for scenic flights during your stay, 
                                        and pilot accommodation. Package rates vary by stay duration.
                                    </p>
                                </div>
                                
                                <div class="helicopter-package-grid">
                                    <label class="helicopter-package-option">
                                        <input type="radio" name="helicopter_package" value="3-nights" />
                                        <div class="package-details">
                                            <span class="package-title">3 Nights Package</span>
                                            <span class="package-hours">4 flying hours + 1 in-property hour</span>
                                            <span class="package-price">R 154,000</span>
                                        </div>
                                    </label>
                                    
                                    <label class="helicopter-package-option">
                                        <input type="radio" name="helicopter_package" value="4-nights" />
                                        <div class="package-details">
                                            <span class="package-title">4 Nights Package</span>
                                            <span class="package-hours">5 flying hours + 2 in-property hours</span>
                                            <span class="package-price">R 192,500</span>
                                        </div>
                                    </label>
                                    
                                    <label class="helicopter-package-option">
                                        <input type="radio" name="helicopter_package" value="5-nights" />
                                        <div class="package-details">
                                            <span class="package-title">5 Nights Package</span>
                                            <span class="package-hours">6 flying hours + 3 in-property hours</span>
                                            <span class="package-price">R 231,000</span>
                                        </div>
                                    </label>
                                    
                                    <label class="helicopter-package-option">
                                        <input type="radio" name="helicopter_package" value="6-nights" />
                                        <div class="package-details">
                                            <span class="package-title">6 Nights Package</span>
                                            <span class="package-hours">7 flying hours + 4 in-property hours</span>
                                            <span class="package-price">R 269,500</span>
                                        </div>
                                    </label>
                                    
                                    <label class="helicopter-package-option">
                                        <input type="radio" name="helicopter_package" value="7-nights" />
                                        <div class="package-details">
                                            <span class="package-title">7 Nights Package</span>
                                            <span class="package-hours">8 flying hours + 5 in-property hours</span>
                                            <span class="package-price">R 308,000</span>
                                        </div>
                                    </label>
                                </div>
                                
                                <div style="margin-top: 15px; padding: 10px; background: #e3f2fd; border-left: 4px solid #2196f3; font-size: 14px;">
                                    <strong>Additional flying time:</strong> R 38,500 per hour available upon request
                                </div>
                            </div>
                        </div>

                        <!-- Add-on Experiences Section -->
                        <div class="form-section">
                            <h3 class="section-title">ADD-ON EXPERIENCES</h3>
                            
                            <div class="experiences-grid">
                                <label class="experience-option">
                                    <input type="checkbox" name="experiences[]" value="mountaineering" />
                                    <span class="checkmark"></span>
                                    Mountaineering
                                </label>
                                <label class="experience-option">
                                    <input type="checkbox" name="experiences[]" value="starlit_safari" />
                                    <span class="checkmark"></span>
                                    Starlit safari
                                </label>
                                <label class="experience-option">
                                    <input type="checkbox" name="experiences[]" value="rhino_darting" />
                                    <span class="checkmark"></span>
                                    Rhino darting
                                </label>
                                <label class="experience-option">
                                    <input type="checkbox" name="experiences[]" value="big_five_game" />
                                    <span class="checkmark"></span>
                                    Big five game
                                </label>
                                <label class="experience-option">
                                    <input type="checkbox" name="experiences[]" value="horse_riding" />
                                    <span class="checkmark"></span>
                                    Horse riding
                                </label>
                                <label class="experience-option">
                                    <input type="checkbox" name="experiences[]" value="yoga_wellness" />
                                    <span class="checkmark"></span>
                                    Yoga and wellness experience
                                </label>
                            </div>
                        </div>

                        <!-- Occasion Section -->
                        <div class="form-section">
                            <h3 class="section-title">OCCASION?</h3>
                            
                            <div class="select-wrapper">
                                <select name="occasion" id="occasion">
                                    <option value="">Please select</option>
                                    <option value="birthday">Birthday</option>
                                    <option value="anniversary">Anniversary</option>
                                    <option value="honeymoon">Honeymoon</option>
                                    <option value="family_vacation">Family Vacation</option>
                                    <option value="corporate">Corporate Retreat</option>
                                    <option value="other">Other</option>
                                </select>
                            </div>
                        </div>

                        <!-- Step Navigation -->
                        <div class="step-navigation">
                            <button type="button" class="btn btn-secondary back-step" data-back="1">
                                BACK
                            </button>
                            <button type="button" class="btn btn-primary next-step" data-next="3">
                                NEXT
                            </button>
                        </div>
                    </div>
                </div>

                <!-- Step 3: Guest Information -->
                <div class="booking-step booking-step-3" data-step="3">
                    <div class="step-content">
                        
                        <h2 class="step-title">Guest information</h2>
                        <p class="step-subtitle">You've selected your dates — now let's get to know you. A few essential details so we can tailor your stay.</p>

                        <!-- Your Information Section -->
                        <div class="form-section">
                            <h3 class="section-title">YOUR INFORMATION</h3>
                            
                            <div class="form-fields">
                                <div class="form-field">
                                    <input type="text" id="full-name" name="full_name" placeholder="Full name" required />
                                </div>
                                
                                <div class="form-field">
                                    <input type="email" id="email" name="email" placeholder="Email address" required />
                                </div>
                                
                                <div class="form-field">
                                    <input type="tel" id="contact-number" name="contact_number" placeholder="Contact number" required />
                                </div>
                                
                                <div class="form-field">
                                    <input type="text" id="home-address" name="home_address" placeholder="Home address" required />
                                </div>
                                
                                <div class="form-field">
                                    <select id="country" name="country" required>
                                        <option value="">Country of residence</option>
                                        <option value="US">United States</option>
                                        <option value="UK">United Kingdom</option>
                                        <option value="CA">Canada</option>
                                        <option value="AU">Australia</option>
                                        <option value="ZA">South Africa</option>
                                        <option value="DE">Germany</option>
                                        <option value="FR">France</option>
                                        <option value="IT">Italy</option>
                                        <option value="ES">Spain</option>
                                        <option value="NL">Netherlands</option>
                                        <option value="BE">Belgium</option>
                                        <option value="CH">Switzerland</option>
                                        <option value="AT">Austria</option>
                                        <option value="SE">Sweden</option>
                                        <option value="NO">Norway</option>
                                        <option value="DK">Denmark</option>
                                        <option value="FI">Finland</option>
                                        <option value="JP">Japan</option>
                                        <option value="SG">Singapore</option>
                                        <option value="HK">Hong Kong</option>
                                        <option value="AE">United Arab Emirates</option>
                                        <option value="BR">Brazil</option>
                                        <option value="AR">Argentina</option>
                                        <option value="IN">India</option>
                                        <option value="CN">China</option>
                                    </select>
                                </div>
                            </div>
                        </div>

                        <!-- How Did You Hear About Us -->
                        <div class="form-section">
                            <h3 class="section-title">HOW DID YOU HEAR ABOUT US?</h3>
                            
                            <div class="select-wrapper">
                                <select name="how_heard" id="how-heard">
                                    <option value="">Please select</option>
                                    <option value="google">Google Search</option>
                                    <option value="social_media">Social Media</option>
                                    <option value="travel_agent">Travel Agent</option>
                                    <option value="word_of_mouth">Word of Mouth</option>
                                    <option value="magazine">Magazine/Publication</option>
                                    <option value="previous_guest">Previous Guest</option>
                                    <option value="other">Other</option>
                                </select>
                            </div>
                        </div>

                        <!-- Special Requests Section -->
                        <div class="form-section">
                            <h3 class="section-title">SPECIAL REQUESTS</h3>
                            
                            <div class="form-field">
                                <textarea name="special_requests" id="special-requests" 
                                          placeholder="Anything else you'd like us to know?"
                                          rows="4"></textarea>
                            </div>
                        </div>

                        <!-- Children's Interests Section -->
                        <div class="form-section">
                            <h3 class="section-title">CHILDRENS INTERESTS (IF APPLICABLE)</h3>
                            
                            <div class="form-field">
                                <textarea name="children_interests" id="children-interests" 
                                          placeholder="What do they love? Stargazing, horses, camping, quad biking?"
                                          rows="3"></textarea>
                            </div>
                        </div>

                        <!-- Disclaimer -->
                        <div class="disclaimer-section">
                            <p class="disclaimer-text">
                                Live availability is shown in real time, but all bookings are subject to final confirmation from the Leobo team.
                            </p>
                        </div>

                        <!-- Step Navigation -->
                        <div class="step-navigation">
                            <button type="button" class="btn btn-secondary back-step" data-back="2">
                                BACK
                            </button>
                            <button type="submit" class="btn btn-primary submit-btn" id="submit-booking">
                                SUBMIT
                            </button>
                        </div>
                    </div>
                </div>

                <!-- Step 4: Thank You -->
                <div class="booking-step booking-step-4" data-step="4">
                    <div class="step-content">
                        <div class="thank-you-content">
                            <h2 class="thank-you-title">Thank you!</h2>
                            <p class="thank-you-message">
                                The final step simply brings everything together and sends off the enquiry.
                            </p>
                        </div>
                    </div>
                </div>
                
                <!-- Hidden fields -->
                <input type="hidden" name="action" value="submit_booking_request">
                <input type="hidden" name="nonce" value="<?php echo wp_create_nonce('leobo_booking_system_nonce'); ?>">
                
            </form>
        </div>

        <!-- Sidebar Summary -->
        <div class="booking-sidebar">
            <div class="sidebar-content">
                
                <!-- Guests Summary -->
                <div class="summary-section">
                    <h4 class="summary-title">GUESTS</h4>
                    <div class="guest-summary">
                        <div class="guest-item">
                            <span class="guest-count" id="sidebar-adults">-</span> adults
                        </div>
                        <div class="guest-item">
                            <span class="guest-count" id="sidebar-children">-</span> children (4+)
                        </div>
                        <div class="guest-item">
                            <span class="guest-count" id="sidebar-babies">-</span> babies (0-3)
                        </div>
                    </div>
                </div>

                <!-- Dates Summary -->
                <div class="summary-section">
                    <h4 class="summary-title">DATES</h4>
                    <div class="dates-summary" id="dates-summary">
                        <div class="date-placeholder">Select your dates</div>
                    </div>
                </div>

                <!-- Pricing Summary -->
                <div class="summary-section">
                    <h4 class="summary-title">ACCOMMODATION PRICE</h4>
                    <div class="price-display">
                        <div class="price-amount" id="accommodation-price">R 120,000</div>
                    </div>
                </div>

                <!-- Optional Extras (Step 2+) -->
                <div class="summary-section optional-extras" style="display: none;">
                    <h4 class="summary-title">OPTIONAL EXTRAS</h4>
                    <div class="extras-summary" id="extras-summary">
                        <div class="price-amount" id="extras-price">R 22,500</div>
                    </div>
                </div>

                <!-- Cost Breakdown (Step 2+) -->
                <div class="cost-breakdown">
                    <h4 class="breakdown-header">COST BREAKDOWN</h4>
                    
                    <!-- Season Information -->
                    <div class="breakdown-section season-info" id="breakdown-season-info" style="display: none;">
                        <div class="breakdown-season-header">
                            <span class="season-badge" id="breakdown-season-badge">Standard Season</span>
                            <span class="season-dates" id="breakdown-season-dates">Jan 6 - Feb 9</span>
                        </div>
                        <div class="breakdown-season-details">
                            <div class="season-rate" id="breakdown-season-rate">R 92,400 per night (up to 4 guests)</div>
                            <div class="season-nights" id="breakdown-season-nights">3 nights × R 92,400</div>
                        </div>
                    </div>
                    
                    <!-- Nightly Breakdown -->
                    <div class="breakdown-section nightly-breakdown" id="breakdown-nightly" style="display: none;">
                        <div class="breakdown-nightly-header">
                            <span class="nightly-title">Nightly Rate Details</span>
                            <button type="button" class="nightly-toggle" onclick="toggleNightlyDetails()">
                                <span class="toggle-text">Show Details</span>
                                <span class="toggle-icon">▼</span>
                            </button>
                        </div>
                        <div class="breakdown-nightly-details" id="breakdown-nightly-details" style="display: none;">
                            <!-- Will be populated by JavaScript -->
                        </div>
                    </div>
                    
                    <div class="breakdown-details">
                        <div class="breakdown-item" id="breakdown-base-accommodation">
                            <span class="breakdown-item-label">Base Accommodation</span>
                            <span class="breakdown-item-detail" id="breakdown-base-detail">Up to 4 guests, 0 nights</span>
                            <span class="breakdown-item-amount" id="breakdown-base-amount">R 0</span>
                        </div>
                        <div class="breakdown-item" id="breakdown-extra-adults" style="display: none;">
                            <span class="breakdown-item-label">Additional Adults</span>
                            <span class="breakdown-item-detail" id="breakdown-extra-adults-detail">0 adults</span>
                            <span class="breakdown-item-amount" id="breakdown-extra-adults-amount">R 0</span>
                        </div>
                        <div class="breakdown-item" id="breakdown-children" style="display: none;">
                            <span class="breakdown-item-label">Children (5-11 years)</span>
                            <span class="breakdown-item-detail" id="breakdown-children-detail">0 children</span>
                            <span class="breakdown-item-amount" id="breakdown-children-amount">R 0</span>
                        </div>
                        <div class="breakdown-item" id="breakdown-babies" style="display: none;">
                            <span class="breakdown-item-label">Babies (0-4 years)</span>
                            <span class="breakdown-item-detail" id="breakdown-babies-detail">0 babies</span>
                            <span class="breakdown-item-amount" id="breakdown-babies-amount">Free</span>
                        </div>
                        <div class="breakdown-item" id="breakdown-christmas-premium" style="display: none;">
                            <span class="breakdown-item-label">Premium Christmas Surcharge</span>
                            <span class="breakdown-item-detail" id="breakdown-christmas-detail">Dec 20 - Jan 1</span>
                            <span class="breakdown-item-amount" id="breakdown-christmas-amount">R 0</span>
                        </div>
                        <div class="breakdown-item" id="breakdown-helicopter" style="display: none;">
                            <span class="breakdown-item-label">Helicopter Package</span>
                            <span class="breakdown-item-detail" id="breakdown-helicopter-detail"></span>
                            <span class="breakdown-item-amount" id="breakdown-helicopter-amount">R 0</span>
                        </div>
                        <div class="breakdown-item" id="breakdown-transfer" style="display: none;">
                            <span class="breakdown-item-label">Transfer</span>
                            <span class="breakdown-item-detail"></span>
                            <span class="breakdown-item-amount" id="breakdown-transfer-amount">R 0</span>
                        </div>
                        <div class="breakdown-item" id="breakdown-experiences" style="display: none;">
                            <span class="breakdown-item-label">Experiences</span>
                            <span class="breakdown-item-detail"></span>
                            <span class="breakdown-item-amount" id="breakdown-experiences-amount">R 0</span>
                        </div>
                        <div class="breakdown-divider"></div>
                        <div class="breakdown-subtotal">
                            <span class="breakdown-subtotal-label">Subtotal</span>
                            <span class="breakdown-subtotal-amount" id="breakdown-subtotal-amount">R 0</span>
                        </div>
                    </div>
                </div>

                <!-- Total Costs (Step 2+) -->
                <div class="summary-section total-costs" style="display: none;">
                    <h4 class="summary-title">TOTAL COSTS</h4>
                    <div class="total-price-display">
                        <div class="price-amount total" id="total-price">R 144,500</div>
                    </div>
                </div>
                
            </div>
        </div>
        
    </div>
    
    <!-- Success/Error Messages -->
    <div id="booking-messages" class="booking-messages">
        <div id="error-message" class="message error-message" style="display: none;"></div>
        <div id="success-message" class="message success-message" style="display: none;"></div>
    </div>
    
</div>
